name: Devops - coderz-backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
      - name: Migrate database
        run: npx sequelize-cli db:migrate

      - name: Restart pm2
        env:
          PORT: ${{ secrets.APP_PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
          HTTPS_PORT: ${{ secrets.HTTPS_PORT }}
        run: ENVIRONMENT=production PORT=$PORT DB_PASSWORD=$DB_PASSWORD DB_USERNAME=$DB_USERNAME DB_NAME=$DB_NAME DB_HOST=$DB_HOST ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET REFRESH_TOKEN_SECRET=$REFRESH_TOKEN_SECRET pm2 restart nodedeploy --update-env
